# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ManyToManyField(related_name='owned_items', to='examapp.Character'),
        ),
    ]
