# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0001_initial'),
        ('examapp', '0002_auto_20171022_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('attributed_to', models.CharField(max_length=255)),
                ('favorite_of', models.ManyToManyField(related_name='favorite_quotes', to='reglogin.User')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_quotes', to='reglogin.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
