# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0001_initial'),
        ('examapp', '0003_auto_20171023_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_of', models.ManyToManyField(related_name='friends', to='reglogin.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='favorite_of',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
