# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0004_auto_20171025_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friend_of',
            new_name='friend',
        ),
    ]
