# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0001_initial'),
        ('examapp', '0005_auto_20171025_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friend_owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='myself', to='reglogin.User'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='my_friend', to='reglogin.User'),
            preserve_default=False,
        ),
    ]
